services:
  postgres:
    image: postgres:17.4
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ndtien2004
      POSTGRES_PASSWORD: ndtien2004
      POSTGRES_DB: MUSIC_DB
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./dags/postgres/create_db_table.sql:/docker-entrypoint-initdb.d/create_db_table.sql
    ports:
      - 5432:5432
    networks:
      - airflow_network

  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - 8082:8080
    networks:
      - airflow_network

  mongo:
    image: mongo:6
    container_name: mongodb_container
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ndtien2004
      MONGO_INITDB_ROOT_PASSWORD: ndtien2004
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
    networks:
      - airflow_network

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    depends_on:
      - mongo
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ndtien2004
      ME_CONFIG_MONGODB_ADMINPASSWORD: ndtien2004
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_URL: mongodb://ndtien2004:ndtien2004@mongo:27017/
    ports:
      - 8081:8081
    networks:
      - airflow_network

  redis:
    image: redis:latest
    container_name: airflow_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - airflow_network

  airflow:
    build: ./dags
    container_name: airflow_webserver
    restart: always
    depends_on:
      - postgres
      - redis
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://ndtien2004:ndtien2004@postgres:5432/MUSIC_DB
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://ndtien2004:ndtien2004@postgres:5432/MUSIC_DB
    ports:
      - "8080:8080"
    networks:
      - airflow_network
    volumes:
      - ./dags:/opt/airflow/dags
      # - ./logs:/opt/airflow/logs
      # - ./plugins:/opt/airflow/plugins
    command: >
      bash -c '(airflow db init &&  airflow users create  --username ndtien2004 --password ndtien2004 --firstname Tien  --lastname Nguyen  --role Admin --email htien225@gmail.com; airflow webserver & airflow scheduler'
networks:
  airflow_network:
    driver: bridge

volumes:
  pgdata:
  mongodata:
