version: '3.8'

services:
  postgres:
    image: postgres:17.4
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./dags/postgres/create_db_table.sql:/docker-entrypoint-initdb.d/create_db_table.sql
    ports:
      - "5432:5432"
    networks:
      - etl_music
  mongo:
    image: mongo:6
    container_name: mongodb_container
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - etl_music
  mongo-express:
    image: mongo-express
    container_name: mongo_express
    depends_on:
      - mongo
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo:27017/
    ports:
      - "8081:8081"
    networks:
      - etl_music

  airflow:
    build:
      context: ./
    container_name: airflow_project
    restart: always
    volumes:
      - ./dags:/opt/airflow/dags
    env_file:
      - .env
    ports:
      - "8080:8080"
    command: >
      bash -c "airflow db init &&
               airflow users create 
               --username ${AIRFLOW_USER} 
               --password ${AIRFLOW_PASSWORD} 
               --firstname ${FIRST_NAME}
               --lastname ${LAST_NAME} 
               --role ${ROLE}
               --email ${AIRFLOW_EMAIL} &&
               airflow webserver & airflow scheduler"
    networks:
      - etl_music
networks:
  etl_music:
    driver: bridge
volumes:
  pgdata:
  mongodata:
